### ISSUE TITLE
problem when using Assets::js and Assets::js_group

### ISSUE THREAD

**Issue by zaherg** [bstrahija/assets-ci#21] opened 2012-06-12 11:39 UTC
```
A PHP Error was encountered
Severity: Notice

Message: Undefined property: stdClass::$js

Filename: libraries/assets.php

Line Number: 833

Backtrace:

File: app\libraries\assets.php
Line: 833
Function: _exception_handler

File: app\libraries\assets.php
Line: 189
Function: _generate_tags
```

i tried  everything but i got this all the time

ps : am using CI 3.0-dev

**Comment by bstrahija** [comment] 2012-06-12 19:30
Could you show me your exact code in the view? What PHP version are you using?

**Comment by zaherg** [comment] 2012-06-13 05:12
``` php
<!DOCTYPE html>
<html>
    <head>  
        <?=Assets::css_group('header',array('bootstrap.css','960_24_col.css','style.css'));?>
        <?=Assets::js_group('header',array('money.min.js'));?>
        <?=$template['metadata'];?>
        <?=Assets::cdn(array('jquery'));?>  
        <title><?php echo $template['title']; ?></title>
    </head>
    <body>
        <div class="container_24">
            <header class="grid_24 header">
                <div class="navbar">
                  <div class="navbar-inner">
                    <div class="container">
                      <?=anchor('/',_t('Msrofi'),'class="brand"');?>
                    </div>
                  </div>
                </div>
            </header>
            <div class="clearfix"></div>
            <div class="grid_5">
                <?=$template['partials']['menu'];?>
            </div>
            <div class="grid_19">
                <div class="page-header">
                    <h1 class="note"><?php echo $template['title']; ?></h1>
                </div>
                    <?php echo $template['body']; ?>                
            </div>
            <div class="clearfix"></div>
            <footer class="grid_24">
                <section class="footer navbar navbar-fixed-bottom">
                    <?=_t('Copyright&copy;');?>
                </section>
            </footer>
        </div>
    </body>
</html>
```

and my money.min.js file is located inside the js folder.
am using php 5.3.8
and my project is using
- CI 3.0dev [ latest code ].
- Phill Template library.
- MX HMVC

**Comment by Creeall** [comment] 2012-06-19 13:23
Hi, no idea if this is related to what I found but you,  bstrahija,  changed the version of the assets.php in assets/1.5.0/libraries/
to 1.5.1.
That seems a bit weird to me. Anyway I got a warning from view when I try to use Assets::css and Asset::js that is resolved if I edit this file sparks/assets/1.5.0/libraries/assets.php :

line 11 : define('ASSETS_VERSION', '1.5.1');

to 1.5.0

**Comment by bstrahija** [comment] 2012-06-19 13:30
I'm still yet to find the cause for the original problem, since I don't have any free time at the moment.

Regarding @Creeall comment, the version on the getsparks website is still at 1.5.0, but the latest version in the head on Github is 1.5.1, but it's not tagged yet because of the issue here. When I fix this (or you can give it a try also :) then I'll tag it as 1.5.1.

**Comment by Creeall** [comment] 2012-06-19 15:50
Thanks for the reply, I went a step ahead putting this 1.5.0 from Git :)
Well I would like to help on this other issue but unable to reproduce this bug, all is working as intended with my CI.

**Comment by RelativeMedia** [comment] 2012-06-20 06:42
I had a similar error when my J's and CSS had syntax errors.

**Comment by bstrahija** [comment] 2012-06-20 07:24
@linuxjuggler could you narrow it down if a specific assets file is causing this problem? I still can reproduce this bug.

**Comment by zaherg** [comment] 2012-06-20 08:27
i tried it with jquery.js the latest one and with money.js (josscrowcroft.github.com/money.js/) ..
and both give me the same problem ..

```
A PHP Error was encountered
Severity: Notice

Message: Trying to get property of non-object

Filename: libraries/assets.php

Line Number: 833
```

this is the second error which i have found ..

**Comment by bstrahija** [comment] 2012-06-20 08:29
I meant that you should remove one of the files. JQuery is probably ok, but does the same thing happen when you remove money.js? Are any of the files alredy compressed (packed)?

**Comment by zaherg** [comment] 2012-06-20 08:30
i have also tried it with dojo 1.7

**Comment by zaherg** [comment] 2012-06-20 08:32
no i use only one js file without which i mean that i tried to load jquery.js ( dev version, none packed ) and i got the error then i tried with money alone (already packed)..
and so on ..

now i will try to load both ..

**Comment by zaherg** [comment] 2012-06-20 08:34
didnt work .. the same even if i load multiple js files ..

**Comment by RelativeMedia** [comment] 2012-06-20 13:29
@linuxjuggler you seem to be using `<?=` which is shorthand for `<?php echo` You don't need to use echo for js and css files.

Try using the following code instead as an example:

``` php
<?php Assets::css_group('header',array('bootstrap.css','960_24_col.css','style.css') ); ?>
<?php Assets::js(array('libs/jquery.js', 'script.js', 'bean.coffee')); ?>
```

### Img Tags

You will need to use echo when using Assets to handle image loading. See the example just below..

``` php
<?php echo Assets::img('logo.png'); ?>
```

**Comment by zaherg** [comment] 2012-06-20 15:59
its not the issue since css works fine, mean while js wont ..

any way thanks for the tip

**Comment by RelativeMedia** [comment] 2012-06-20 16:15
just trying to pick a needle out of a haystack, no problem.. When i get some more time i'll look into it more.

**Comment by bstrahija** [comment] 2012-08-10 09:07
This should be fixed in the latest version.

**Closed as completed by bstrahija** 2012-08-10 09:07 UTC
